modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Magistu/Epic-Knights-Dark-Ages/issues"
displayURL="https://github.com/Magistu/Epic-Knights-Dark-Ages"
license = "MIT"
[[mods]]
modId = "darkagesarmory"
version = "${version}"
displayName = "Epic Knights: Dark Ages"
authors = ["Magistu", "SuperSus890", "Desperate_bork", "StaxiHD", "Skydog"]
credits = []
description = '''
Adds equipment of the Dark Ages
'''

[[dependencies.darkagesarmory]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkagesarmory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkagesarmory]]
modId = "magistuarmory"
mandatory = true
versionRange = "[8.6,)"
ordering = "AFTER"
side = "BOTH"