package com.magistuarmory.darkages.item.armor;

import com.magistuarmory.darkages.EpicKnightsDarkAges;
import com.magistuarmory.darkages.config.ArmorConfig;
import com.magistuarmory.item.armor.ArmorType;
import dev.architectury.platform.Platform;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;

public class AddonArmorTypes
{
	public static final ArmorConfig ARMOR_CONFIG = EpicKnightsDarkAges.CONFIG.armor;

	public static final ArmorType BALYK_SOOK_LAMELLAR = new ArmorType(new ResourceLocation("darkagesarmory", "balyk_sook_lamellar"), new ResourceLocation("darkagesarmory:balyk_sook_lamellar"), ARMOR_CONFIG.balykSookLamellar.toughness, 0.0f, new Integer[] { 0, 0, ARMOR_CONFIG.balykSookLamellar.chestplateDurability, 0 }, new Integer[] { 0, 0, ARMOR_CONFIG.balykSookLamellar.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.balykSookLamellar.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType EASTERN_RICH_KAFTAN = new ArmorType(new ResourceLocation("darkagesarmory", "eastern_rich_kaftan"), new ResourceLocation("default"), ARMOR_CONFIG.easternRichKaftan.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.easternRichKaftan.bootsDurability, 0, ARMOR_CONFIG.easternRichKaftan.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.easternRichKaftan.bootsDefense, 0, ARMOR_CONFIG.easternRichKaftan.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.easternRichKaftan.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType BIRKA_TUNIC = new ArmorType(new ResourceLocation("darkagesarmory", "birka_tunic"), new ResourceLocation("darkagesarmory:tunic"), ARMOR_CONFIG.birkaTunic.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.birkaTunic.bootsDurability, 0, ARMOR_CONFIG.birkaTunic.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.birkaTunic.bootsDefense, 0, ARMOR_CONFIG.birkaTunic.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.birkaTunic.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType LOMBARD_LAMELLAR = new ArmorType(new ResourceLocation("darkagesarmory", "lombard_lamellar"), new ResourceLocation("default"), ARMOR_CONFIG.lombardLamellar.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.lombardLamellar.bootsDurability, 0, ARMOR_CONFIG.lombardLamellar.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.lombardLamellar.bootsDefense, 0, ARMOR_CONFIG.lombardLamellar.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.lombardLamellar.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BYRNIE = new ArmorType(new ResourceLocation("darkagesarmory", "byrnie"), new ResourceLocation("default"), ARMOR_CONFIG.byrnie.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.byrnie.bootsDurability, 0, ARMOR_CONFIG.byrnie.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.byrnie.bootsDefense, 0, ARMOR_CONFIG.byrnie.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.byrnie.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType NORTHERN_GAMBESON = new ArmorType(new ResourceLocation("darkagesarmory", "northern_gambeson"), new ResourceLocation("default"), ARMOR_CONFIG.northernGambeson.toughness, 0.0f, new Integer[] { 0, 0, ARMOR_CONFIG.northernGambeson.chestplateDurability, 0 }, new Integer[] { 0, 0, ARMOR_CONFIG.northernGambeson.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.northernGambeson.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType COMMON_HAUBERK = new ArmorType(new ResourceLocation("darkagesarmory", "common_hauberk"), new ResourceLocation("default"), ARMOR_CONFIG.commonHauberk.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.commonHauberk.bootsDurability, 0, ARMOR_CONFIG.commonHauberk.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.commonHauberk.bootsDefense, 0, ARMOR_CONFIG.commonHauberk.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.commonHauberk.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType RICH_BYRNIE = new ArmorType(new ResourceLocation("darkagesarmory", "rich_byrnie"), new ResourceLocation("default"), ARMOR_CONFIG.richByrnie.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.richByrnie.bootsDurability, 0, ARMOR_CONFIG.richByrnie.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.richByrnie.bootsDefense, 0, ARMOR_CONFIG.richByrnie.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.richByrnie.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VENDEL_GREAVES = new ArmorType(new ResourceLocation("darkagesarmory", "vendel_greaves"), new ResourceLocation("darkagesarmory:vendel_greaves"), ARMOR_CONFIG.vendelGreaves.toughness, 0.0f, new Integer[] { 0, ARMOR_CONFIG.vendelGreaves.leggingsDurability, 0, 0 }, new Integer[] { 0, ARMOR_CONFIG.vendelGreaves.leggingsDefense, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.vendelGreaves.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BANDENHELM = new ArmorType(new ResourceLocation("darkagesarmory", "bandenhelm"), new ResourceLocation("darkagesarmory:bandenhelm"), ARMOR_CONFIG.bandenhelm.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.bandenhelm.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.bandenhelm.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.bandenhelm.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BENTY_GRANGE_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "benty_grange_helmet"), new ResourceLocation("darkagesarmory:benty_grange_helmet"), ARMOR_CONFIG.bentyGrangeHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.bentyGrangeHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.bentyGrangeHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.bentyGrangeHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BIRKA_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "birka_helmet"), new ResourceLocation("darkagesarmory:birka_helmet"), ARMOR_CONFIG.birkaHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.birkaHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.birkaHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.birkaHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BROA_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "broa_helmet"), new ResourceLocation("darkagesarmory:broa_helmet"), ARMOR_CONFIG.broaHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.broaHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.broaHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.broaHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType COPPERGATE_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "coppergate_helmet"), new ResourceLocation("darkagesarmory:coppergate_helmet"), ARMOR_CONFIG.coppergateHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.coppergateHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.coppergateHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.coppergateHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DESJATINNA_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "desjatinna_helmet"), new ResourceLocation("darkagesarmory:desjatinna_helmet"), ARMOR_CONFIG.desjatinnaHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.desjatinnaHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.desjatinnaHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.desjatinnaHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_DESJATINNA_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "gilded_desjatinna_helmet"), new ResourceLocation("darkagesarmory:desjatinna_helmet"), ARMOR_CONFIG.gildedDesjatinnaHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gildedDesjatinnaHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gildedDesjatinnaHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.gildedDesjatinnaHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_TJELE_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "gilded_tjele_helmet"), new ResourceLocation("darkagesarmory:tjele_helmet"), ARMOR_CONFIG.gildedTjeleHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gildedTjeleHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gildedTjeleHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.gildedTjeleHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GJERMUNDBU_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "gjermundbu_helmet"), new ResourceLocation("darkagesarmory:gjermundbu_helmet"), ARMOR_CONFIG.gjermundbuHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gjermundbuHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gjermundbuHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.gjermundbuHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GORZUCHY_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "gorzuchy_helmet"), new ResourceLocation("darkagesarmory:gorzuchy_helmet"), ARMOR_CONFIG.gorzuchyHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gorzuchyHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.gorzuchyHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.gorzuchyHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LOKRUME_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "lokrume_helmet"), new ResourceLocation("darkagesarmory:lokrume_helmet"), ARMOR_CONFIG.lokrumeHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.lokrumeHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.lokrumeHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.lokrumeHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType PECS_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "pecs_helmet"), new ResourceLocation("darkagesarmory:pecs_helmet"), ARMOR_CONFIG.pecsHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.pecsHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.pecsHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.pecsHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType SOMME_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "somme_helmet"), new ResourceLocation("darkagesarmory:somme_helmet"), ARMOR_CONFIG.sommeHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.sommeHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.sommeHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.sommeHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType STAFFORSHIRE_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "stafforshire_helmet"), new ResourceLocation("darkagesarmory:staffordshire_helmet"), ARMOR_CONFIG.stafforshireHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.stafforshireHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.stafforshireHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.stafforshireHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType SUTTON_HOO_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "sutton_hoo_helmet"), new ResourceLocation("darkagesarmory:sutton_hoo"), ARMOR_CONFIG.suttonHooHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.suttonHooHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.suttonHooHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.suttonHooHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LEIDEN_BANDHELMET = new ArmorType(new ResourceLocation("darkagesarmory", "leiden_bandhelmet"), new ResourceLocation("darkagesarmory:bandenhelm"), ARMOR_CONFIG.leidenBandhelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.leidenBandhelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.leidenBandhelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.leidenBandhelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType TELJE_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "telje_helmet"), new ResourceLocation("darkagesarmory:tjele_helmet"), ARMOR_CONFIG.teljeHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.teljeHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.teljeHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.teljeHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType ULTUNA_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "ultuna_helmet"), new ResourceLocation("darkagesarmory:valsgarde"), ARMOR_CONFIG.ultunaHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.ultunaHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.ultunaHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.ultunaHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VALSGARDE_5 = new ArmorType(new ResourceLocation("darkagesarmory", "valsgarde_5"), new ResourceLocation("darkagesarmory:valsgarde"), ARMOR_CONFIG.valsgarde5.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.valsgarde5.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.valsgarde5.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.valsgarde5.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VALSGARDE_8 = new ArmorType(new ResourceLocation("darkagesarmory", "valsgarde_8"), new ResourceLocation("darkagesarmory:valsgarde_8"), ARMOR_CONFIG.valsgarde8.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.valsgarde8.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.valsgarde8.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.valsgarde8.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VENDEL_1 = new ArmorType(new ResourceLocation("darkagesarmory", "vendel_1"), new ResourceLocation("darkagesarmory:vendel_1_helmet"), ARMOR_CONFIG.vendel1.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.vendel1.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.vendel1.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.vendel1.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VENDEL_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "vendel_helmet"), new ResourceLocation("darkagesarmory:vendel_14_helmet"), ARMOR_CONFIG.vendelHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.vendelHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.vendelHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.vendelHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VERDEN_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "verden_helmet"), new ResourceLocation("darkagesarmory:verden_helmet"), ARMOR_CONFIG.verdenHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.verdenHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.verdenHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.verdenHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType WOLLASTON_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "wollaston_helmet"), new ResourceLocation("darkagesarmory:wollaston_helmet"), ARMOR_CONFIG.wollastonHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.wollastonHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.wollastonHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.wollastonHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType YARM_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "yarm_helmet"), new ResourceLocation("darkagesarmory:yarm_helmet"), ARMOR_CONFIG.yarmHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.yarmHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.yarmHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.yarmHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType STROMOVKA_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "stromovka_helmet"), new ResourceLocation("darkagesarmory:stromovka_helmet"), ARMOR_CONFIG.stromovkaHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.stromovkaHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.stromovkaHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.stromovkaHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType ZLIN_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "zlin_helmet"), new ResourceLocation("darkagesarmory:zlin_helmet"), ARMOR_CONFIG.zlinHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.zlinHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.zlinHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.zlinHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType KERCH_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "kerch_helmet"), new ResourceLocation("darkagesarmory:kerch_helmet"), ARMOR_CONFIG.kerchHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.kerchHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.kerchHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.kerchHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType TROSINO_HELMET = new ArmorType(new ResourceLocation("darkagesarmory", "trosino_helmet"), new ResourceLocation("darkagesarmory:trosino_helmet"), ARMOR_CONFIG.trosinoHelmet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.trosinoHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.trosinoHelmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.trosinoHelmet.enabled, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType PATTERNED_EASTERN_HAT = new ArmorType(new ResourceLocation("darkagesarmory", "patterned_eastern_hat"), new ResourceLocation("darkagesarmory:eastern_hat"), ARMOR_CONFIG.patternedEasternHat.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.patternedEasternHat.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.patternedEasternHat.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.patternedEasternHat.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType EASTERN_HAT = new ArmorType(new ResourceLocation("darkagesarmory", "eastern_hat"), new ResourceLocation("darkagesarmory:eastern_hat"), ARMOR_CONFIG.easternHat.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.easternHat.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.easternHat.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.easternHat.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType PILLBOX_CAP = new ArmorType(new ResourceLocation("darkagesarmory", "pillbox_cap"), new ResourceLocation("darkagesarmory:pillbox_cap"), ARMOR_CONFIG.pillboxCap.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.pillboxCap.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.pillboxCap.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.pillboxCap.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType OATERNED_PILLBOX_CAP = new ArmorType(new ResourceLocation("darkagesarmory", "oaterned_pillbox_cap"), new ResourceLocation("darkagesarmory:pillbox_cap"), ARMOR_CONFIG.oaternedPillboxCap.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.oaternedPillboxCap.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.oaternedPillboxCap.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.oaternedPillboxCap.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

	public static final ArmorType FUR_PILLBOX_CAP = new ArmorType(new ResourceLocation("darkagesarmory", "fur_pillbox_cap"), new ResourceLocation("darkagesarmory:pillbox_cap"), ARMOR_CONFIG.furPillboxCap.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.furPillboxCap.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.furPillboxCap.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.furPillboxCap.enabled, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));

}
